select_tool:
  description: "Select a tool, framework, simulator..."
  type: select
  options:
    vunit: "VUnit"
    ghdl: "GHDL"
    cocotb: "cocotb"
  value: "ghdl"

execution_mode:
  description: "Select the execution mode."
  type: select
  options:
    gui: "GUI"
    cmd: "Command line"
  value: "cmd"

waveform_viewer:
  description: "Select the waveform viewer. For GTKWave you need to install it."
  type: select
  options:
    tool: "Tool GUI"
    vcdrom: "VCDrom"
    gtkwave: "GTKWave"
  value: "tool"
