name: Check pull request
on:
  pull_request:
    branches:
      - main
jobs:
  #############################################################################
  # Check merge
  #############################################################################
  merge_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the pull request is mergeable to main
        run: |
          if [[ "$GITHUB_HEAD_REF" == 'dev' ]]; then exit 0; else exit 1; fi;