name: Linux

on: [push]

jobs:
  test-linter:
    runs-on: ubuntu-18.04
    container:
      image: docker://terostech/multi-simulator:1.0.2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script testLinter
  # ****************************************************************************
  # ****************************************************************************
  test-templates:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script testTemplates
  # ****************************************************************************
  # ****************************************************************************
  test-stm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script test-stm
  # ****************************************************************************
  # ****************************************************************************
  test-ProjectManager:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script testProjectManager
  # ****************************************************************************
  test-Parser:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script testParser
