name: Macos

on: [push]

jobs:
  # test-linter:
  #   runs-on: ubuntu-18.04
  #   container:
  #     image: docker://terostech/multi-simulator:1.0.0
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testLinter
  # # ****************************************************************************
  # # ****************************************************************************
  # test-templates:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest]
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testTemplates
  # ****************************************************************************
  # ****************************************************************************
  test-documenter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script testDocumenter
  # ****************************************************************************
  # ****************************************************************************
  test-ProjectManager:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script testProjectManager
  # ****************************************************************************
  # test-Parser:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest]
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testParser
