name: Tests

on: [push]

jobs:
  # test-linter:
  #   runs-on: ubuntu-18.04
  #   container:
  #     image: docker://terostech/multi-simulator:1.0.0
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testLinter
  # # ****************************************************************************
  # # ****************************************************************************
  # test-templates:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest, ubuntu-18.04]
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testTemplates
  # # ****************************************************************************
  # # ****************************************************************************
  # test-documenter:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest, ubuntu-18.04]
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testDocumenter
  # # ****************************************************************************
  # # ****************************************************************************
  # test-ProjectManager:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest, ubuntu-18.04]
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testProjectManager
  # # ****************************************************************************
  # test-Parser:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-18.04]
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Test
  #       run: |
  #         npm install .
  #         npm run-script testParser

  test-Parser-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install –msvs_version=2012
          npm -g install node-pre-gyp
          npm -g install node-gyp
          npm install
          npm run-script testParser
