name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://terostech/multi-simulator:1.0.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm install .
          npm run-script testLinter
