name: Test_unit_suites

on: [push]

jobs:
  test-suites:
    runs-on: ubuntu-18.04
    container:
      image: docker://terostech/multi-simulator:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test_suites
        run: |
          npm run-script testSuites
